name: Build RedPill DSM loader

on: 
  workflow_dispatch:
    inputs:
      dsmodel:
        description: 'Input Full DSM model [DS3622xs+|RS4021xs+|DVA3221|DS918+|DS920+|DS3615xs]'
        required: true
        default: 'DS3622xs+'
      os_version:
        description: 'Must build DSM7.1 and after DSM versions'
        required: true
        default: '42621'
#       pat-address:
#         description: 'Pat file URL'
#         required: true
#         default: 'https://global.download.synology.com/download/DSM/release/7.1/42621/DSM_DS3622xs%2B_42621.pat'
jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build dsm 7.1
        id: build-dsm-71
        run: |
            bash build-universal-7.1.sh ${{github.event.inputs.dsmodel}} ${{github.event.inputs.os_version}} ${{github.event.inputs.pat-address}}
      - name: Archive loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-${{github.event.inputs.dsmodel}}_7.1-loader
          path: output/redpill-*.img
